sudo: required
services:
  - docker

before_install:
  - docker build -t pavneshkaushal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pavneshkaushal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-836200856165"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"


